sonar.projectKey=platform-evaluation-backend
sonar.projectName=Platform Evaluation Backend
sonar.projectVersion=0.0.1-SNAPSHOT
sonar.sourceEncoding=UTF-8

# Source code
sonar.sources=src/main
sonar.tests=src/test

# Java binaries
sonar.java.binaries=target/classes

# Code coverage with JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions
sonar.exclusions=**/config/**,**/entity/**,**/dto/**
sonar.test.exclusions=**/test/**
