server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/platforme?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
app.jwt.secret=THIS_IS_A_VERY_LONG_SECRET_KEY_CHANGE_ME_1234567890_ABCDEFG
app.jwt.expiration-ms=86400000

# Docker configuration
docker.host=tcp://localhost:2375
docker.tls.verify=false
gamix.container.port-range-start=9100
gamix.container.port-range-end=9200
