spring.application.name=eureka-server
server.port=8761

# Eureka Server Configuration - Ne pas s'enregistrer soi-meme
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Dashboard
eureka.server.enable-self-preservation=false

